name: TaskBoard CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  ci:
    name: TaskBoard CI
    runs-on: ubuntu-latest

    steps:

      # Step 1: Get the source code
      - name: Checkout code
        uses: actions/checkout@v5

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22

      # Step 3: Install frontend dependencies
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      # Step 4: Build frontend
      - name: Build frontend
        working-directory: frontend
        run: npm run build

      # Step 5: Install backend dependencies
      - name: Install backend dependencies
        working-directory: backend
        run: npm ci

      # Step 6: Validate backend
      - name: Validate backend
        working-directory: backend
        run: node --check src/server.js

      # Step 7: Run tests
      # Tests will be added to the project later.
      - name: Run tests
        run: echo "No automated tests configured yet"

      # Step 8: Build Docker images
      - name: Build frontend Docker image
        run: docker build -t taskboard-frontend:ci ./frontend

      - name: Build backend Docker image
        run: docker build -t taskboard-backend:ci ./backend

      # Step 9: Login to GitHub Container Registry
      - name: Login to GHCR
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 10: Push frontend image
      - name: Push frontend image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker tag taskboard-frontend:ci \
            ghcr.io/pradhumnaadhikari/taskboard-frontend:latest

          docker push \
            ghcr.io/pradhumnaadhikari/taskboard-frontend:latest

      # Step 11: Push backend image
      - name: Push backend image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker tag taskboard-backend:ci \
            ghcr.io/pradhumnaadhikari/taskboard-backend:latest

          docker push \
            ghcr.io/pradhumnaadhikari/taskboard-backend:latest
