name: TaskBoard CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  ci:
    name: TaskBoard CI
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Install backend dependencies
        working-directory: backend
        run: npm ci

      - name: Validate backend
        working-directory: backend
        run: node --check src/server.js

      - name: Run tests
        run: echo "No automated tests configured yet"

      - name: Build frontend Docker image
        run: docker build -t taskboard-frontend:ci ./frontend

      - name: Build backend Docker image
        run: docker build -t taskboard-backend:ci ./backend

      # AWS authentication
      - name: Configure AWS credentials
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      # ECR login
      - name: Login to Amazon ECR
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: aws-actions/amazon-ecr-login@v2

      # Push frontend
      - name: Push frontend image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker tag taskboard-frontend:ci \
            ${{ secrets.ECR_REGISTRY }}/taskboard-frontend:latest

          docker push \
            ${{ secrets.ECR_REGISTRY }}/taskboard-frontend:latest

      # Push backend
      - name: Push backend image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker tag taskboard-backend:ci \
            ${{ secrets.ECR_REGISTRY }}/taskboard-backend:latest

          docker push \
            ${{ secrets.ECR_REGISTRY }}/taskboard-backend:latest
